// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bopyvewcbbwlntdddfxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvcHl2ZXdjYmJ3bG50ZGRkZnhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTQ3NzksImV4cCI6MjA2ODY3MDc3OX0.B-votrb3wo8l8hwJBL-SmWBHRSF5GyO5RY0XL1r8JSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);